apiVersion: v1
version: 6.3.0
appVersion: 6.3.0
name: podinfo
engine: gotpl
description: Podinfo Helm chart for Kubernetes
home: https://github.com/stefanprodan/podinfo
maintainers:
- email: stefanprodan@users.noreply.github.com
  name: stefanprodan
sources:
- https://github.com/alessio4tech/podinfo
kubeVersion: ">=1.19.0-0"
