apiVersion: v1
kind: Service
metadata:
  annotations:
    component-name: sas-scr-{{ .Values.name }}
  labels:
    deployment: sas-scr-{{ .Values.name }}
    app: sas-scr-{{ .Values.name }}
  name: sas-scr-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: apiserver
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: sas-scr-{{ .Values.name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}