apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scr2
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '>4.0.x'
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
    image:
       repository: ghcr.io/stefanprodan/podinfo
       tag: 6.2.0

